### PR TITLE
port of all latest changes from ccu.io ical adapter

### PR DESCRIPTION
**Pull request by jens-maus**
This pull request ports two important changes/fixes from the last ccu.io ical adapter version over to the iobroker version and also integrates some new changes regarding text substations and colorizing text.

### CODE REVIEW

**Comment by GermanBluefox** [comment]
Does it work?

**Comment by jens-maus** [comment]
Well, here it actually works in my productive iobroker environment.

**Comment by jens-maus** [comment]
One of the things you might have to check/adapt is perhaps the russian translation of terms I added after my russian college provided me these translations :)

**Comment by jens-maus** [comment]
Any chance of getting my changes merged to the official ioBroker.ical repository?

**Comment by GermanBluefox** [comment]
There is a new version of ical - 0.5.0
Can you check it please if it work? I have no ical.

P.S. Thanks for noting me, I lost your pull request.

**Comment by jens-maus** [comment]
Which ical version do you mean? the ical iobroker updater is at version 1.1.1 here. Don't know what you mean with 0.5.0?

**Comment by GermanBluefox** [comment]
I mean [npm-ical](https://www.npmjs.com/package/ical)
It is new version there, but I have on idea if it works with iobroker.ical. But now I checked the changes and can say, that it will work. I update the version of ical-npm to 0.5.0 and will publish ioBroker.ical

**Pull request merged**
