### PR TITLE
add several new features

### PR DESCRIPTION
**Pull request by twonky4**
add filter for events, issue #63;
add data.countTomorrow, issue #72;
support next days events, issue #41;
handle events with same start and end date, issue #81;

### CODE REVIEW

**Comment by Apollon77** [comment]
Great, thank you, merged, NPM publish too or Forum test before?

**Comment by twonky4** [comment]
It so much, it should be tested before npm publish.

**Comment by Apollon77** [comment]
Can you creaate test thread in "Tester" forum ?!

**Comment by twonky4** [comment]
Done: https://forum.iobroker.net/viewtopic.php?f=36&t=18650

**Pull request merged**
