### PR TITLE
setState ack flag bug fix

### PR DESCRIPTION
**Pull request by Scrounger**
ack flag is set to true which cause problems with other adapters e.g. scenes

### CODE REVIEW

**Comment by Apollon77** [comment]
Is this relevant for "custom state values" configured? Csan you show more details of the config or tell some more details please?

**Comment by Scrounger** [comment]
If you would like to control e.g. the position of a knx shutter or hm shutter with the event function, then this will not work because the ack flag is sent.

**Comment by Apollon77** [comment]
I will close the PR and will do it configurable ... because else it would be a breaking change in behaviour. I post here once done for you test test please, ok?

**Comment by Apollon77** [comment]
@Scrounger Thank you for testing

**Pull request closed without merging**
