### PR TITLE
Option to handle all events as fullday events.

### PR DESCRIPTION
**Pull request by BuZZy1337**
Added the option to handle all Events as fullday events.
(Hide start and endtime of events)

### CODE REVIEW

**Comment by GermanBluefox** [comment]
When this option could be helpful ?

**Comment by jens-maus** [comment]
Good question. I also wonder about the actual real use case for this PR?!?

**Comment by BuZZy1337** [comment]
First i changed the code only for my own requirements because my garbage disposal plan app only allowed to export the dates of collection with time of "06:00-06:30" in the events and i dont want to have it shown like "Tomorrow 06:00-06:30 - ...". Then i saw the question on the iobroker board how to hide the time of events ( http://forum.iobroker.net/viewtopic.php?t=3595&start=20#p62511 ) 
User andyb:
(Ich fände es ja gut, wenn man konfigurieren könnte ob Uhrzeit angezeigt werden sollen oder nicht)
.... and after that i decided to push my changes to github. 
Also i use the ical Adapter for an "overview" of the Events.. I dont really need to know the time of events when looking at my view in iobroker vis - important is only the day of the events.

**Comment by jens-maus** [comment]
But this is in contradicting what the iCal standard allows. There you can perfectly define all-day events. So IMHO you should better add your events as all day events instead of forcing the front-end (iBroker.ical) to hide times. IMHO this doesn't make real sense.

**Comment by BuZZy1337** [comment]
Thats correct, but in ioBroker i only want an "overview" of upcoming events.. The start and end time is not important for me at that point and hiding the start and end time would save a lot of space on the views/widgets in VIS.
On the other side i want to keep the ability to see the start and end time of the events on my phone.

**Comment by GermanBluefox** [comment]
Ok. I think we can merge it.

2017-09-15 10:41 GMT+02:00 BuZZy <notifications@github.com>:

**Pull request merged**
