### PR TITLE
fixed 3 issues

### PR DESCRIPTION
**Pull request by twonky4**
* Fixed html for disabled colorize (issue #73)
* Fixed timezone handling for events during change from daylight saving time back to standard time

### CODE REVIEW

**Comment by Apollon77** [comment]
travis test red, have restarted them ... mysterious

**Comment by twonky4** [comment]
I think it was a timing issue, because the second run was successful. But nevertheless it founds a possible problem. If a system has no timezone.

**Comment by Apollon77** [comment]
I will soon remove the file ".settings/.gitignore" from this PR and then merge ... just that you know ... maybe setting .settings in global gitignore is a good idea?

Thank you very much!!

**Comment by Apollon77** [comment]
Thank you, will go out now. I will also post in forum (hopefully I find all threads)

**Pull request merged**
