### PR TITLE
Added analysis for private events

### PR DESCRIPTION
**Pull request by BasGo**

### CODE REVIEW

**Comment by jens-maus** [comment]
Please explain: What is this PR all about? Please add some technical description where and explain!

**Comment by BasGo** [comment]
This PR extends the ical adapter by analyzing if an event has a private flag set. For Google Calendar items Google sets a class "PRIVATE" to an event and this extension forwards this flag into a new field "_private" of the internal ical data structure.

The reason to implement this extension is that I have the need to differ between private and non-private calendar items, because non-private events will be shown on a central placed display in our house.

**Comment by jens-maus** [comment]
Thanks for explaination. Please provide an example .ical file so that I can more easily review this PR.

**Review by jens-maus — CHANGES_REQUESTED** [review]

**Comment by BasGo** [comment]
The attachment contains a sample ical file for testing.
[reduced.ics.zip](https://github.com/iobroker-community-adapters/ioBroker.ical/files/6449975/reduced.ics.zip)

**Comment by jens-maus** [comment]
> The attachment contains a sample ical file for testing.
> [reduced.ics.zip](https://github.com/iobroker-community-adapters/ioBroker.ical/files/6449975/reduced.ics.zip)

Thanks for this. For the records: The relevant `VEVENT` section is this:

```
BEGIN:VEVENT
DTSTART:20210507T100000Z
DTEND:20210507T110000Z
DTSTAMP:20210510T062900Z
UID:040000008200E00074C5B7101A82E00800000000C10A74DFBE41D701000000000000000
 010000000E9F7F42EE80E164DBD356F5D117D9269
CLASS:PRIVATE
CREATED:20210505T145648Z
DESCRIPTION:
LAST-MODIFIED:20210505T145648Z
LOCATION:
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:Arztbesuch
TRANSP:OPAQUE
END:VEVENT
```

Note the `CLASS:PRIVATE` thought.

**Review by jens-maus — APPROVED** [review]

**Comment by Apollon77** [comment]
LGTM too

**Comment by Apollon77** [comment]
PS: The version changelog needs to be moved one level down ... can be done after merge too

**Pull request merged**
