### PR TITLE
 fix timezone problem and add support for exception in recurrences

### PR DESCRIPTION
**Pull request by twonky4**
event dates of rrule doesn't contains timezone data and have to added.
fixes issue #33 and #59.

### CODE REVIEW

**Comment by Apollon77** [comment]
Great and thank you! I did not found the time so far to look into it.

Can you please check the failed recurring test that throws error:

```
TypeError: Cannot read property 'getTime' of undefined
    at addOffset (/home/travis/build/ioBroker/ioBroker.ical/tmp/node_modules/iobroker.ical/main.js:237:22)
    at processData (/home/travis/build/ioBroker/ioBroker.ical/tmp/node_modules/iobroker.ical/main.js:265:33)
    at Immediate.<anonymous> (/home/travis/build/ioBroker/ioBroker.ical/tmp/node_modules/iobroker.ical/main.js:222:25)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

also see https://travis-ci.org/ioBroker/ioBroker.ical/jobs/438741075#L1783

and https://github.com/ioBroker/ioBroker.ical/blob/master/test/testAdapterRecurringException.js

Thank you!

**Comment by twonky4** [comment]
Good to have tests, there was still an issue. It's now fixed.

What's about this comment? https://github.com/ioBroker/ioBroker.ical/blob/2998b64e54cae1c48a4feeac61b6ac03b1c9c28d/test/testAdapterRecurringException.js#L289-L290

Is it related to my change?

**Comment by Apollon77** [comment]
If your version really addresses #33 then yes, then you could remove the commends from the last block there and see if it worked (if test is correct) ... I always thought that #33 is also because of a bug in the ical library that is doing these kind of changes not correct

**Comment by Apollon77** [comment]
Perfect!!

**Comment by twonky4** [comment]
It wasn't a bug in ical library or only a light bug. The exception array variable `ev.recurrences` is an array but have to be an object because it is a associative array. `JSON.stringify` doesn't display such wrong declared variables correctly.

So back to topic: Exception in recurrences was not supported jet in ioBroker.ical. I added the support.

**Comment by Apollon77** [comment]
Cool. If you have a fix for iCal lib send in a pr there too. And reference here. I organize a release!

**Comment by twonky4** [comment]
pr already created: https://github.com/jens-maus/node-ical/pull/4

**Comment by Apollon77** [comment]
Or do we need no iCal lib update?

**Comment by twonky4** [comment]
iCal lib update is not needed for ioBroker.ical

**Comment by Apollon77** [comment]
Interesting ... nodejs 4 Tests broken there but not here ... we need to check that ;-)

**Comment by Apollon77** [comment]
Great then I merge and update directly later as soon Kids are finally in bed ;-)

**Comment by twonky4** [comment]
Great thx! Then my wife will be happy, as her night shifts are displayed correctly again 😄

**Comment by Apollon77** [comment]
1.6.2 released to npm, tomorrow in latest ...

**Pull request merged**
