### PR TITLE
No more font-weight bold

### PR DESCRIPTION
**Pull request by Pix---**
I have deleted "font-weight: bold" in html-output as style commands further than colour set should be placed in vis.

### CODE REVIEW

**Comment by twonky4** [comment]
Why are you removed the `font-weight` but keep the `color` attribute? I would remove both or nothing.

Why we shouldn't keep the `font-weight`? Couldn't it re-set it via `class` attribute to `normal`?

I think it's will initially set because inexperienced user wouldn't use css but want a different style between days.

**Comment by Apollon77** [comment]
Please also think about backward cmpatibility fort the existing (mostly unexperienced)  users! What exactly will change for them? Could I please see a "i use the generated html before/after result"?

**Comment by twonky4** [comment]
As far as I can see a event that start yesterday is not `bold`.

**Comment by Pix---** [comment]
I have checked _ical.0.data.html_. This is what it looks like:
ical html
Every entry is set to `bold`.

I think we should close this discussion now that we have spent too much time for that small issue. I will continue formatting the html with vis' css-editor and !important.

**Comment by twonky4** [comment]
For a event the starts yesterday and will end tomorrow night the html will be:
```html
<span style="font-weight: bold; color: white"><span class="icalNormal iCal-event-calendar">&#8594; 18.11. 00:00</span></span>
<span style="font-weight: normal; color: white"><span class='icalNormal2 iCal-event-calendar2'> EventThreeDays</span></span>
```

**Comment by twonky4** [comment]
@Pix---: But i think you are right. We shouldn't use the style tag at all. But instead of remove the style it should move to css classes.

**Comment by GermanBluefox** [comment]
Any news here?

**Comment by twonky4** [comment]
@GermanBluefox: I wouldn't merge this PR and I think it can be closed.

**Pull request closed without merging**
