### PR TITLE
Added compact mode and option to use short years

### LINKED ISSUE #93: Add Support for Compact mode (js-Controller 2.0 Feature)
The upcoming version 2.0.0 of js-controller will support a new mode for low memory devices. For this, a few minor adjustments to the adapter must be made. Please follow these instructions: https://forum.iobroker.net/viewtopic.php?f=24&t=20387#p213466

### PR DESCRIPTION
**Pull request by BasGo**
fixes #93

### CODE REVIEW

**Comment by Apollon77** [comment]
Sorry but you also need to adapt the testing ... or better: the defaults for the new options should be defined so that testing stays green. Then the compact mode is not correct ... 

And added testing for your new feature would be great too. The adapter is very complex because of all those settings options and so we have proper automated testing to make sure not to break existing functionality!

**Comment by BasGo** [comment]
Sounds good, should I stop this PR and re-work and re-create two new PRs (compact mode & 3-value year output)? It's up to you ;)

**Comment by twonky4** [comment]
Now it doesn't matter. You can continue with this pull request.

I also thought about https://github.com/ioBroker/ioBroker.ical/pull/94/files#diff-7a9076d6d94e62c13d641aa71f19ae8eR476 the: `date.text.trim()`.

Did you check where the spaces come from? I think it's better to not adding them instead of removing them afterwards.

**Comment by BasGo** [comment]
As I've seen they have been added to "prepare" a readable output (date together with time). Due to some configuration possibilities (output as date or string like tomorrow, all days events and much more) it seems to be a kind of lazy creation which possibly results in keeping whitespaces at the end.

I agree and prefer to have them not to be added ... but this would be a bigger change ;-)

**Comment by twonky4** [comment]
Then it makes more sence to split it up.
1. compact mode
2. short year
3. remove spaces

;-)

**Comment by BasGo** [comment]
Now I'm a bit confused: "split them up" means that I'll re-work all three changes and submit them by separate pull requests (with year handling as 3-value config and prevention of unnecessary whitespaces)?

**Comment by Apollon77** [comment]
@twonky4 thank you for taking over :-)

**Comment by BasGo** [comment]
Sorry, closed by mistake (Handy).

**Comment by twonky4** [comment]
In my option its better to work iterative. So finish one issue by one. If you put all fixes in one pull request it may takes time (impl. -> review -> test) to release all changes.

Btw.: v1.7.1 was released yet, you can add your changes to this version also.

**Comment by BasGo** [comment]
Changes will be sent by separate PRs.

**Pull request closed without merging**
