### PR TITLE
EXDATE support patch

### PR DESCRIPTION
**Pull request by jens-maus**
This PR fixes/implements support for EXDATE parameter in ics calendar files.

### CODE REVIEW

**Comment by jens-maus** [comment]
@GermanBluefox Thanks for providing me collaborator access to this repo. So I guess it is fine now that I merge this PR. However, you are probably the only use with publish permission to npm, right?

**Comment by Apollon77** [comment]
Yes he is :-) But a note is mostly enough :-)
You did everything needed for it to be only the publish :-)

**Comment by jens-maus** [comment]
Ok. merged this PR. So @GermanBluefox, please publish it at npm

**Comment by GermanBluefox** [comment]
@jens-maus you can push to npm now yourself. :) Please confirm, that you read this.

**Comment by jens-maus** [comment]
Ok thanks for the info. How did you grant permission for that?

**Comment by GermanBluefox** [comment]
in the according directory: ```npm owner add jens-maus```

**Pull request merged**
